var files_dup =
[
    [ "bullet.cpp", "bullet_8cpp.html", null ],
    [ "bullet.h", "bullet_8h.html", "bullet_8h" ],
    [ "gameManager.cpp", "game_manager_8cpp.html", "game_manager_8cpp" ],
    [ "gameManager.h", "game_manager_8h.html", "game_manager_8h" ],
    [ "matrixObject.cpp", "matrix_object_8cpp.html", null ],
    [ "matrixObject.h", "matrix_object_8h.html", "matrix_object_8h" ],
    [ "mine.cpp", "mine_8cpp.html", null ],
    [ "mine.h", "mine_8h.html", "mine_8h" ],
    [ "move.h", "move_8h.html", "move_8h" ],
    [ "movingObject.cpp", "moving_object_8cpp.html", null ],
    [ "movingObject.h", "moving_object_8h.html", "moving_object_8h" ],
    [ "objectType.h", "object_type_8h.html", "object_type_8h" ],
    [ "orientation.h", "orientation_8h.html", "orientation_8h" ],
    [ "player1Tank.cpp", "player1_tank_8cpp.html", null ],
    [ "player2Tank.cpp", "player2_tank_8cpp.html", "player2_tank_8cpp" ],
    [ "playerTank.h", "player_tank_8h.html", "player_tank_8h" ],
    [ "tank.cpp", "tank_8cpp.html", null ],
    [ "tank.h", "tank_8h.html", "tank_8h" ],
    [ "tanksGame.cpp", "tanks_game_8cpp.html", "tanks_game_8cpp" ],
    [ "tanksGame.h", "tanks_game_8h.html", "tanks_game_8h" ],
    [ "unmovingObject.cpp", "unmoving_object_8cpp.html", null ],
    [ "unmovingObject.h", "unmoving_object_8h.html", "unmoving_object_8h" ],
    [ "wall.cpp", "wall_8cpp.html", null ],
    [ "wall.h", "wall_8h.html", "wall_8h" ]
];